fix: use np.ptp() not ndarray.ptp() (removed in numpy 2.0)
CI (numpy 2.x) failed test_mosaic_canvas with AttributeError: 'numpy.ndarray'
object has no attribute 'ptp'. np.ptp(arr) works on all numpy versions.